apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world
  description: Example
  labels:
    example.com/custom: foo
  annotations:
    example.com/service-discovery: artistweb
  tags:
    - java
    - certificate
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
  certificates:
    - client_name: Test
      expiration_date: 10/10/2022
    - client_name: Test 2
      expiration_date: 10/10/2020
  contact_info:
    - contact_type: lead
      name: Brian
      email: brian@email.com
      team: EGIS
      role: team lead
    - contact_type: tech_lead
      name: Betty
      email: betty@email.com
      team: EGIS
      role: Tech Lead
spec:
  type: website
  lifecycle: production
  owner: egis-team
  system: EGIS
  domain: bar
